version: '3.8'

services:
  frontend:
    build:
      context: ./car-price-frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always

  backend:
    build:
      context: ./webservice
      dockerfile: ./Dockerfile
    container_name: backend
    restart: always
    
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"  # Expose HTTPS as well, if needed
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - frontend
      - backend